CREATE TABLE TRAINING
(
    TRAINING_ID NUMBER (10) NOT NULL,
    TRAINING_TITLE VARCHAR2(100) NOT NULL,
    STARTDATE DATE,
    CONSTRAINT TRAINING_PK PRIMARY KEY (TRAINING_ID)

);

CREATE SEQUENCE TRAINING_SEQ START WITH 1;
