CREATE TABLE PARTICIPATION
(
    PARTICIPATION_ID NUMBER(10) NOT NULL,
    EVENT_ID NUMBER(10) NOT NULL,
    ATTENDEE_ID NUMBER(10),
    CONSTRAINT PARTICIPATION_PK PRIMARY KEY (PARTICIPATION_ID),
    CONSTRAINT EVENT_FK FOREIGN KEY (EVENT_ID) REFERENCES EVENTS (ID),
    CONSTRAINT ATTENDEE_FK FOREIGN KEY (ATTENDEE_ID) REFERENCES ATTENDEES (ID)
);

CREATE SEQUENCE PARTICIPATION_SEQ START WITH 1;

select ATTENDEES.Name as Participant, EVENTS.EVENTNAME AS Eventname
  from EVENTS join PARTICIPATION on EVENTS.ID = PARTICIPATION.EVENT_ID 
  join ATTENDEES on ATTENDEES.ID = PARTICIPATION.ATTENDEE_ID
 
var htmldb_add_message = "The dates overlaps with one of the other Events. Please click ok to proceed";
var dd= new Date();
var a = apex.item( "P5_STARTDATE" ).getValue()
debugger;
if(a>dd){
    var htmldb_add_message = "";
}